# Ignore false positive from Rails' ActionText and ActiveStorage
ActionText::RichText:
  enabled: false
ActiveStorage::Attachment:
  enabled: false
ActiveStorage::Blob:
  enabled: false
ActiveStorage::VariantRecord:
  enabled: false

User:
  password:
    ColumnPresenceChecker:
      enabled: false
  encrypted_password:
    NullConstraintChecker:
      enabled: false
  index_users_on_reset_password_token:
    UniqueIndexChecker:
      enabled: false

AdminUser:
  password:
    ColumnPresenceChecker:
      enabled: false
  encrypted_password:
    NullConstraintChecker:
      enabled: false
  index_admin_users_on_reset_password_token:
    UniqueIndexChecker:
      enabled: false
