detectors: # for now don't care for describing core model classes and classes based on gem DSLs (well named)
  IrresponsibleModule:
    enabled: false

directories:
  "app/avo/filters": # uses avo DSL
    UtilityFunction:
      enabled: false
  "app/controllers":
    InstanceVariableAssumption:
      enabled: false
  #   NestedIterators:
  #     max_allowed_nesting: 2
  #   UnusedPrivateMethod:
  #     enabled: false
  # "app/helpers":
  #   UtilityFunction:
  #     enabled: false
  # "app/mailers":
  #   InstanceVariableAssumption:
  #     enabled: false
  # "app/models":
  #   InstanceVariableAssumption:
  #     enabled: false

exclude_paths:
  - config/application.rb
  - db/migrate
  - .git-hooks/**/*.rb
